version: '3'

tasks:
  build:
    cmds:
      - go build  main.go
  build:ui:
    cmds:
      - cd ui && pnpm run build
  swag:
    cmds:
      - swag init
  start:
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go run main.go start
  start:ui:
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - cd ui && pnpm run dev

